## 7章: データ操作

In [17]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [18]:
import pandas as pd

# CSVファイルを読み込む
# df: DataFrame
df = pd.read_csv('Chapter7_1.csv')
print(df)

   ID  日本語     英語
0   1  りんご  apple
1   2  ぶどう  grape
2   3  レモン  lemon

### excel対応

In [20]:

# 作成したデータから、Excelファイルへ書き込む
df = pd.DataFrame(data = {
    'ID': [1, 2, 3],
    '日本語': ['りんご', 'ぶどう', 'レモン'],
    '英語': ['apple', 'grape', 'lemon']
})
display(df)

writer = pd.ExcelWriter('Chapter7_5.xlsx')
df.to_excel(writer, sheet_name='Sheet1', index=True)
writer.close()

   ID  日本語     英語
0   1  りんご  apple
1   2  ぶどう  grape
2   3  レモン  lemon

### フィルタリング

In [24]:
# データを定義する
df = pd.DataFrame(data = {
    'ID': [1, 2, 3],
    '日本語': ['りんご', 'ぶどう', 'レモン'],
    '英語': ['apple', 'grape', 'lemon']
})
display(df)
print("------------------")

# 「ID」列が2以上のデータを抽出する
filter = df[(df['日本語'] == "オレンジ")]
print(filter)

   ID  日本語     英語
0   1  りんご  apple
1   2  ぶどう  grape
2   3  レモン  lemon

------------------
Empty DataFrame
Columns: [ID, 日本語, 英語]
Index: []

### 集計

In [26]:
# データを定義する
df = pd.DataFrame(data = {
    'ID': [1, 2, 3],
    '日本語': ['りんご', 'ぶどう', 'レモン'],
    '英語': ['apple', 'grape', 'lemon'],
    '値段': [100, 200, 600]
})

# 「値段」列の平均値を計算する
mean = df['値段'].mean()
print(mean)

max = df['値段'].max()
print(max)

300.0
600

### 変換

In [28]:

# データを定義する
df = pd.DataFrame(data = {
    'ID': [1, 2, 3],
    '日本語': ['りんご', 'ぶどう', 'レモン'],
    '英語': ['apple', 'grape', 'lemon'],
    '値段': [100, 200, 600]
})

# これくらいならこちらでも可
print(df["値段"] * 10)
df["値段10倍"] = df["値段"] * 10
display(df)

# 値を10倍にしてcostに返す関数「transform」を定義
def transform(cost):
    return cost * 10

# 関数transformを適用し、transform_resultに格納
transform_result= df['値段'].apply(transform)
print(transform_result)

0    1000
1    2000
2    6000
Name: 値段, dtype: int64

   ID  日本語     英語   値段  値段10倍
0   1  りんご  apple  100   1000
1   2  ぶどう  grape  200   2000
2   3  レモン  lemon  600   6000

## 8章: データ結合

In [29]:
import pandas as pd


# CSVファイルを読み込む
df = pd.read_csv('Chapter7_1.csv')

# [1:3]: 2行目から3行目、[0, 2]: 1列目と3列目を抽出してdf2に格納
df2 = df.iloc[1:3, [0, 2]]

print(df2)

   ID     英語
1   2  grape
2   3  lemon

### 型変換

In [30]:
import pandas as pd

# データを定義する
df = pd.DataFrame({
    'ID': ['1', '2', '3'],
    'point': ['80', '90', '70']
})

print(df.dtypes)

print("\n---------------------\n")

# point列を数値型に変換する
df['point'] = pd.to_numeric(df['point'])

# df.dtypes: データ型を出力
print(df.dtypes)

ID       object
point    object
dtype: object

---------------------

ID       object
point     int64
dtype: object

### 文字列への変換（あまり使わない）

In [11]:
import pandas as pd


# データフレームの作成
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 28, 22, 35],
    'City': ['New York', 'Los Angeles', 'London', 'Tokyo']
}
df = pd.DataFrame(data)

# to_string()使用前
print("to_string()使用前:")
print(df)
print(type(df))

print("\n---------------------\n")

# to_string()使用後
df_string = df.to_string()
print("to_string()使用後:")
print(df_string)
print(type(df_string))

to_string()使用前:
      Name  Age         City
0    Alice   24     New York
1      Bob   28  Los Angeles
2  Charlie   22       London
3    David   35        Tokyo
<class 'pandas.core.frame.DataFrame'>

---------------------

to_string()使用後:
      Name  Age         City
0    Alice   24     New York
1      Bob   28  Los Angeles
2  Charlie   22       London
3    David   35        Tokyo
<class 'str'>

### locの扱い方

In [31]:
import pandas as pd
# データを定義する
df = pd.DataFrame({
    'ID': [1, 2, 3],
    '日本語': ['りんご', 'ぶどう', 'レモン'],
    '英語': ['apple', 'grape', 'lemon']
})
# 列名を指定
name_col = df.loc[:, '日本語']
print(name_col)
print(type(name_col))

0    りんご
1    ぶどう
2    レモン
Name: 日本語, dtype: object
<class 'pandas.core.series.Series'>

### 結合

In [32]:
import pandas as pd


# データフレームの作成
df1 = pd.DataFrame({'ID': [1, 2],
                    '日本語': ['りんご', 'ぶどう'],
                    '英語': ['apple', 'grape']
})
display(df1)
print("-----------------------------------")


df2 = pd.DataFrame({'ID': [3, 4],
                    '日本語': ['レモン', 'バナナ'],
                    '英語': ['lemon', 'banana']
})
display(df2)

print("-----------------------------------")

# 縦結合
result = pd.concat([df1, df2], axis=0)

# 結果の表示
display(result)

   ID  日本語     英語
0   1  りんご  apple
1   2  ぶどう  grape

-----------------------------------

   ID  日本語      英語
0   3  レモン   lemon
1   4  バナナ  banana

-----------------------------------

   ID  日本語      英語
0   1  りんご   apple
1   2  ぶどう   grape
0   3  レモン   lemon
1   4  バナナ  banana